//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey_hairstyle
    {
        public int Id { get; set; }
        public Nullable<int> Journey_AncientcostumeID { get; set; }
        public string Style1 { get; set; }
        public string Style2 { get; set; }
        public string Style3 { get; set; }
    
        public virtual Journey_Ancientcostume Journey_Ancientcostume { get; set; }
    }
}
