//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journey()
        {
            this.Favorites = new HashSet<Favorite>();
            this.Journey_Ancientcostume = new HashSet<Journey_Ancientcostume>();
            this.Journey_Grouptype = new HashSet<Journey_Grouptype>();
            this.Journey_Travellertype = new HashSet<Journey_Travellertype>();
            this.Order_Details = new HashSet<Order_Details>();
            this.Journey_Contact = new HashSet<Journey_Contact>();
        }
    
        public int Id { get; set; }
        public string JourneyName { get; set; }
        public Nullable<System.DateTime> JourneyDate { get; set; }
        public string JourneyContent { get; set; }
        public string JourneyShort { get; set; }
        public string Sights { get; set; }
        public string Stay { get; set; }
        public string Stay_img1 { get; set; }
        public string Stay_img2 { get; set; }
        public string Stay_img3 { get; set; }
        public string Stay_title { get; set; }
        public string Stay_text { get; set; }
        public string ExpenseItems { get; set; }
        public string Remarks { get; set; }
        public string AssemblyPlace { get; set; }
        public string DailyItinerary { get; set; }
        public string EditImage { get; set; }
        public string Location { get; set; }
        public string Sights_img1 { get; set; }
        public string Sights_img2 { get; set; }
        public string Sights_img3 { get; set; }
        public string Sights_title { get; set; }
        public string Sights_text { get; set; }
        public Nullable<int> Journey_StaysId { get; set; }
        public string TraveItems { get; set; }
        public Nullable<decimal> MakeUpExpenses { get; set; }
        public Nullable<decimal> Photo { get; set; }
        public Nullable<decimal> Transportation { get; set; }
        public Nullable<decimal> StayExpenses { get; set; }
        public Nullable<decimal> Activity { get; set; }
        public Nullable<decimal> CarFare { get; set; }
        public Nullable<decimal> Food { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_Ancientcostume> Journey_Ancientcostume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_Grouptype> Journey_Grouptype { get; set; }
        public virtual Journey_Stays Journey_Stays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_Travellertype> Journey_Travellertype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_Contact> Journey_Contact { get; set; }
    }
}
