//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey_Stays
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journey_Stays()
        {
            this.Journeys = new HashSet<Journey>();
        }
    
        public int Id { get; set; }
        public string StayName { get; set; }
        public string StayImage { get; set; }
        public string StayInfo { get; set; }
        public string Type { get; set; }
        public Nullable<int> Num_of_bed { get; set; }
        public Nullable<int> Max_of_exlra_prople { get; set; }
        public Nullable<int> Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey> Journeys { get; set; }
    }
}
