//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Order_Customerinfo = new HashSet<Order_Customerinfo>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Customersname { get; set; }
        public string E_mail { get; set; }
        public string Phone { get; set; }
        public string TwId { get; set; }
        public string Address { get; set; }
        public string SelectPerson { get; set; }
        public string Selectfood { get; set; }
        public string Selectchild { get; set; }
        public string Message { get; set; }
        public Nullable<int> JourneyId { get; set; }
        public string JourneyName { get; set; }
        public string JourneyContent { get; set; }
        public string Sights { get; set; }
        public string Stay { get; set; }
        public string ExpenseItems { get; set; }
        public string MakeUpExpenses { get; set; }
        public string Photo { get; set; }
        public string Transportation { get; set; }
        public string CarFare { get; set; }
        public string StayExpenses { get; set; }
        public string Activity { get; set; }
        public string Food { get; set; }
        public string AssemblyPlace { get; set; }
        public string DailyItinerary { get; set; }
        public string custom { get; set; }
        public string makeup { get; set; }
        public string hair { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Customerinfo> Order_Customerinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
