//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Statusrecord
    {
        public int Id { get; set; }
        public Nullable<int> Oldstatus { get; set; }
        public Nullable<int> Newstatus { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
