//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Id { get; set; }
        public string Customersname { get; set; }
        public string E_mail { get; set; }
        public string Phone { get; set; }
        public string Paymentmethod { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Orderfullamount { get; set; }
        public Nullable<System.DateTime> Paymentdate { get; set; }
        public string Servicebase { get; set; }
        public Nullable<System.DateTime> Departuredate { get; set; }
        public Nullable<System.DateTime> Returndate { get; set; }
        public string Journeyname { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public string Groupnumber { get; set; }
        public string Orderstate { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> JourneyID { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual Order Order { get; set; }
    }
}
