//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey_Ancientcostume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journey_Ancientcostume()
        {
            this.Journey_costumestyle = new HashSet<Journey_costumestyle>();
            this.Journey_makeupstyle = new HashSet<Journey_makeupstyle>();
            this.Journey_hairstyle = new HashSet<Journey_hairstyle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JourneyID { get; set; }
        public string Hairstyle { get; set; }
        public string Makeupstyle { get; set; }
        public string Costumestyle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_costumestyle> Journey_costumestyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_makeupstyle> Journey_makeupstyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey_hairstyle> Journey_hairstyle { get; set; }
        public virtual Journey Journey { get; set; }
    }
}
