//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey_Contact
    {
        public int Id { get; set; }
        public string Customer { get; set; }
        public string MakeupArtist { get; set; }
        public string Photographer { get; set; }
        public string Contact { get; set; }
        public string Message { get; set; }
        public string InstantMessage { get; set; }
        public string LineGroup { get; set; }
        public Nullable<int> JourneyID { get; set; }
    
        public virtual Journey Journey { get; set; }
    }
}
