//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcDBEntities : DbContext
    {
        public AcDBEntities()
            : base("name=AcDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Journey_Contact> Journey_Contact { get; set; }
        public virtual DbSet<Journey_Grouptype> Journey_Grouptype { get; set; }
        public virtual DbSet<Journey_Travellertype> Journey_Travellertype { get; set; }
        public virtual DbSet<Order_Customerinfo> Order_Customerinfo { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order_Statusrecord> Order_Statusrecord { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Journey_costumestyle> Journey_costumestyle { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Journey_makeupstyle> Journey_makeupstyle { get; set; }
        public virtual DbSet<Journey_Ancientcostume> Journey_Ancientcostume { get; set; }
        public virtual DbSet<Journey_hairstyle> Journey_hairstyle { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Journey_Stays> Journey_Stays { get; set; }
        public virtual DbSet<Journey> Journeys { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
