//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_costume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Customerinfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IDnumber { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Creditcard { get; set; }
        public Nullable<int> People { get; set; }
        public string Eatinghabits { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
